### ISSUE TITLE
Still use multiple Activities

### ISSUE THREAD

**Issue by sirvon** [bluelinelabs/Conductor#101]
I would like to still include some Activities in my app.
I'm not getting how to include other activities within the controller paradigm.

I understand controllers are for view based screens, but at times there are
libraries that use activities to represent the ui that I would like to include
in the app.

How does multiple activities play in using conductor?

Can you point me to any code examples.

say I am at my home controller and a user wants to open smooch ui,
smooch comes with an existing activity that opens via...

```java
ConversationActivity.show(this);
```

How do I transition to that Activity or any other activity outside of the main one that holds the router?

thanks!

**Comment by adi1133** [comment]
The router resides inside the activity, for each new activity you need a new router. You can use Conductor with multiple activities, interactions can be done using dependency injection, the startActivityForResult() method and other means. Do not rely on setTargetController() between different activities since it relies on a shared router instance.

Warning, rant below

I found it better to have a single activity even when using fragments. Android has bad support for multiple activities.
For example android keeps all the views of unfinished activities from the active task in memory, this can easily cause an out of memory error if you navigate to multiple activities inside your app. I think this is why the new activity template from Android Studio creates a fragment inside each activity.
Fragments and Conductor avoid this issue by doing view cleanup when the view is not on screen.

**Comment by EricKuck** [comment]
@adi1133's description of using multiple `Activity`s with Conductor is great. The only thing I'd add relative to your question is that you'd call `ConversationActivity.show(getActivity())` from within a `Controller` to use Smooch.

**Comment by sirvon** [comment]
So how would i go about start fragments from a controller.
It seems thats exactly what i really want to kno is how u do
various things from controller to presenter..

**Comment by EricKuck** [comment]
Sorry for the late response. Ideally you wouldn't be starting any Fragments, as this library is meant to be a Fragment replacement. If you were going to start one, however, you'd get the FragmentManager from the host Activity and start it like normal. There is a `getActivity` call that you can use to get the host, so there's nothing stopping you from doing things the way you always have.
