### ISSUE TITLE
Lifecycle diagram doesn't include save/restore

### ISSUE THREAD

**Issue by plusCubed** [bluelinelabs/Conductor#111]
Why was it [changed](https://github.com/bluelinelabs/Conductor/pull/80/commits/b67ce76697cfd50292bd50e3035fa0d17aff9b93) between 1.1.6 and 2.0 to remove the save/restore methods (other than simplification)?

Is the old diagram still valid for 2.0? If it is, I think a link to the full diagram is better than having only the simplified one.

**Comment by EricKuck** [comment]
The old diagram is not valid for 2.0. The 1.x version of conductor tried to include save/restore in the controller lifecycle, but had some issues due to the wide variety of reasons the system could call `onSaveInstanceState`.  Trying to tie that to lifecycle was a nightmare and was frankly a bad idea. It's now been removed from the lifecycle and is just called whenever the system calls `onSaveInstanceState`.

**Comment by plusCubed** [comment]
I see. I just read #100, which also makes clear the view state methods - I think some documentation (perhaps just a link to #100) in the README on the save/restore methods would be great, as these are essentially "lifecycle" methods, though not connected to any specific point in time.
