### ISSUE TITLE
onDetached & Nougat multitasking

### ISSUE THREAD

**Issue by duckinferno** [bluelinelabs/Conductor#114]
I'm keen on giving this framework a stab but I noticed in the lifecycle diagram that onDetach is called when the Activity is paused.  In 7.0+, onPause is called when an activity no longer has focus and onStop is called when the activity is no longer visible at all.  This is important re: multitasking; if onDetach is called on my app while it's still visible alongside the app I'm currently interacting with, presumably I've stopped any view updates and the user will essentially just be viewing a screenshot of my app... you get the picture.

I spent 10 mins rooting around the code but I couldn't see any onPaused hooks detaching views; the closest detaching lifecycle event I could find was onDestroy.  However 10 minutes is not long enough to become familiar with the code base.  Is the diagram wrong?  Will Conductor work nicely with Android N's multitasking?

**Comment by PaulWoitaschek** [comment]
Did you actually observe the changes not appearing in your app?

By having a look at the source code [attach](https://github.com/bluelinelabs/Conductor/blob/c153e29273c2645ec7cc33cdab77777db400165f/conductor/src/main/java/com/bluelinelabs/conductor/Controller.java#L828) you can see that it's the views onAttach.

Its working with my app, my listeners get removed in onDetatch and I see view updates while in split screen mode.

**Comment by grandstaish** [comment]
This is something I'm curious about too, though only for theoretical reasons because I don't currently have an app that uses Conductor. On one of the ADB podcast episodes, they discussed the intricacies of multi-tasking on Android, and when `onPause`/`onStop` would get called. `onPause` will get called when you are interacting with another app in another window, and `onStop` will get called when you're app is completely backgrounded. Therefore doing everything inside of `onPause` doesn't make sense. The examples they gave were that if you were playing video, you'd want to stop the playback in `onStop` (because if you did it in `onPause` then you wouldn't be able to watch the video while multi-tasking). On the other hand, if you were writing a camera app, you'd want to release the camera in `onPause` incase another app wants to use it. So to extend to the question, does conductor provide an easy way to get the `onPause`/`onStop` callbacks?

**Comment by duckinferno** [comment]
@grandstaish exactly.  To answer your question directly, I believe that the conductor has activity lifecycle event hooks you can override.

However it seems like behaviour in N+ should be to have the controller detach your views in onStop.  It'd be great if a dev or someone more familiar with Conductor on 7.0 could chip in.

**Comment by EricKuck** [comment]
That diagram is a bit misleading now that I look at it again. I'll update this soon. 

To clarify, the Activity's `onPause` method doesn't necessarily cause the Controller's `onDetach` to be called (it only does this if the view actually does detach as a result of `onPause`). In the case of multi-window, `onDetach` is NOT called, so I believe everything's working correctly. If for whatever reason you needed to know that the app was in multi-window mode and was no longer focused, you can override the `onActivityPause` method to get that notification.

Does the way it's currently working not meet anyone's needs when it comes to multi-window mode?

**Comment by duckinferno** [comment]
No, I think that's the answer we were looking for.  I'll leave the issue open for you to close once the diagram is updated.   Cheers :)

**Comment by ZakTaccardi** [comment]
Lets say you attach a controller to a router after the activity's `onStart()` has been called.

Does `Controller#onActivityStarted()` get called for this controller? Or does it miss this event?

If it does, then this library meets my needs 110%.

**Comment by EricKuck** [comment]
The `onActivityXXXX` callbacks will only be called when those events occur, so `onActivityStarted()` will not be called if you attach a controller to an Activity after it's been started. What's the use-case for desiring this?

**Comment by nomisRev** [comment]
@ZakTaccardi I'm also curious what your use case for this is.

**Comment by nomisRev** [comment]
I have a demo on this. I could create a PR to integrate this into the demo.

**Comment by EricKuck** [comment]
@nomisRev Sorry for the radio silence. If you have a demo that you feel would be good to show people, by all means please PR away!

**Comment by cerisier** [comment]
Bouncing back on this.

I am using Conductor in my company's app along with the Rx lifecycle since we are using RxJava extensively.

We just realised now that `onPause` / `onStop` is not handled by `RxController` and so we find ourselves having all our Rx pipes and UI behaviour bound to `DESTROY`. That leads us having a lot of heavy UI related stuff happening.

1. Is this something I would have to implement myself or am I missing something here ? 
2. Is there a way to have the same sort of mechanism and be able to detach the controller while retaining the view ?

**Comment by EricKuck** [comment]
@cerisier This should now be fixed in the latest snapshot. Assuming it all looks good I'll be pushing a new version soonish.

**Comment by duckinferno** [comment]
Thanks for updating the diagram.
