### ISSUE TITLE
Production Ready ?

### ISSUE THREAD

**Issue by leonardo2204** [bluelinelabs/Conductor#16]
First of all, excellent job, another excellent library to "bypass" the Fragments nightmare !
I have some doubts regarding this lib:

1. Is it production ready ? I mean, can I start an app based on this lib to go to prod ?
2. How can I reference the Activity/Fragment ? e.g: To login using the Facebook SDK you need to pass the activity or fragment reference, not a Context.
3. What is the difference between using this lib or Flow ?
4. Does the lib support out-of-the-box saving/restoring view states ? e.g. navigating from one "screen" to another and going back, everything will be as it was left off ? (even if app gets killed by Android ?)

Sorry to bother and thanks again!

**Comment by EricKuck** [comment]
Thanks for checking it out. Here's answers:

1. Yep, it's production ready. This started as an internal library for our company and is currently in use in 3 production apps. No issues to report so far.
2. You can reference the Activity with the `getActivity()` method that each `Controller` has.
3. Flow is a lot of work to get started with. So much boilerplate. This is meant to be a library that you can get up and running with very quickly. We tried to use Flow when it was first released (and a few times since) and just couldn't make it work for us.
4. It does support saving and restoring view states out of the box. If you check out the [lifecycle diagram](https://github.com/bluelinelabs/Conductor/blob/develop/docs/Controller%20Lifecycle.jpg) you'll see there are convenient `onSaveViewState()` and `onRestoreViewState()` methods.

**Comment by leonardo2204** [comment]
Thank you for the lightning-fast reply !
I really thought about the same about Flow, it is tricky to get used to, and the Key stuff needs too much boilerplate code.
I just checked out the code from Conductor and it's a very concise and clean code, soon I'll start contributing to the library !

Thanks again for the answer and awesome work !

PS: Do you have some milestone to the library ? Kinda of a "what's next ?"

**Comment by EricKuck** [comment]
No milestones as of yet (it's fit all our needs so far), but we'll be constantly iterating on it as needs come up.
