### ISSUE TITLE
Better Documentation for Change Handlers

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#173]
It would be good to have a better documentation for change handlers. Especially about how to use them and how not to use them.

I just experienced an annoying bug where I my controllers appeared multiple times over each other.
It was because I was reusing the change handler instance.

For example this could documented as "do only use an instance of a change handler for one change".

**Comment by nomisRev** [comment]
I have a small presentation on Conductor I gave a while back. And giving again at GDG Istanbul. https://github.com/nomisRev/conductor-demo-google-devfest2016

It comes with a little bit more advanced code like Dagger, Anko and MVP. But the demo on the Conductor github page is super awesome imho. I have dedicated a seperate part to ChangeHandlers because I think they're absolutely awesome. I would be willing to clean that code up some more and fork it to this page, perhaps as a Kotlin demo. Or just as an advanced demo with MVP/Dagger because I saw a issue pass by last week about that 2.

I do have some more free time soon and I am willing to pitch in because I just think this library is awesome. What were you thinking, just add more info in the code with Javadoc? Or do some kind of wiki on the github?

Any thoughts any1?

**Comment by EricKuck** [comment]
I agree that the documentation is sparse. I'd love to see a full wiki! This has been on my to-do list forever, but haven't had enough time to do write it up well. If anyone wants to talk about collaborating on some docs, I'd be very open to that.

BTW, watched your presentation @nomisRev. Great stuff!

**Comment by nomisRev** [comment]
I'd be more than happy to help with a full wiki! I think it would be a great addition to this awesome lib. Just not sure where to start.

Haha, thanks!

**Comment by PaulWoitaschek** [comment]
Maybe also throw an exception if change handlers are reused (can this be detected)? I faced some very strange bugs where change listeners were not called because the handlers were reused.

**Comment by EricKuck** [comment]
@PaulWoitaschek e7c195d9105d457abe3a9bba0cc7f525230233a5 now ensures that ControllerChangeHandlers won't be reused. If a developer attempts to reuse one, it'll internally copy the handler into a new instance and use that instead. The library was already doing that in most places, but this commit puts it all into a single location to ensure it happens every time.

I'll close this issue and open another one for doing a wiki.

**Comment by PaulWoitaschek** [comment]
Thanks very much for your great work!

**Comment by PaulWoitaschek** [comment]
What I don't understand and what I can't find any documentation about is `removesFromViewOnPush`. @EricKuck 

What does that do and when is it useful?
