### ISSUE TITLE
Example for RouterPagerAdapter usage

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#182]
I just discovered RouterPagerAdapter. It would be great if you could give an example when this class is useful and add it to the demo project.

**Comment by EricKuck** [comment]
I mentioned it in the release notes I just published a second ago. It's really just an alternative PagerAdapter that should be used when a page needs to have navigation of its own. This is a bit of an edge case and probably won't be used too often.

ControllerPagerAdapter is designed to have 1 controller per page. RouterPagerAdapter is designed to let you do whatever you want with a page, since the Router is what you'll be interacting with.

I'm not sure if a demo is really needed for this, but I'd be happy to add one if people want it.
