### ISSUE TITLE
onSaveViewState is not calling for the first push another controller

### ISSUE THREAD

**Issue by fAns1k** [bluelinelabs/Conductor#185]
i have a root controller that is call `onSaveViewState` when it shows for the first time.
that's because lib `LifecycleHandler` calls `onActivitySaveInstanceState` in `ActivityHostedRouter`, so my root contoller has flag `hasSavedViewState` as true.

And when i try to push another controller above of the original one - method `onSaveViewState` is not called, because of condition below

`Controller`
```
if (!isBeingDestroyed && !hasSavedViewState) {
                saveViewState(view);
           }
```

**Comment by fAns1k** [comment]
i debugged it deeper - and it seems that it comes up when i use android 23+ permission request and permission request dialog shows up, so activity turns into "PAUSE" state.

**Comment by EricKuck** [comment]
I'm not following what your issue is. Why is `onSaveViewState` being called when the controller shows? 

While permissions request do pause your Activity, they don't cause `onSaveInstanceState` to be called, so your controllers shouldn't be calling `onSaveViewState` just because you've requested a permission.

**Comment by fAns1k** [comment]
thanks for your response.
ok, i debugged this issue and it calls somehow. i will recheck what the cause is.

**Comment by EricKuck** [comment]
While I haven't seen the issue you're referring to occur, I suppose it is possible that an `onSaveInstanceState` could be called without detaching the host Activity from the window, which would have caused the old logic to not work. This should be fixed with the above commit. If you're still seeing issues, please reopen.
