### ISSUE TITLE
Controller popup not working onBackPressed()

### ISSUE THREAD

**Issue by burhanrashid52** [bluelinelabs/Conductor#194]
When we apply pushController on `onCreateView()` or `onAttach(View view)` with this code:
`getRouter().pushController(RouterTransaction.with(new Home3Controller()));`
so at that time when we click on back button its does not pop up the view but its works fine when we put this on button click event manually

**Comment by duckinferno** [comment]
Does your activity override onBackPressed and feed the event to your router?

```
@Override
public void onBackPressed() {
    if (!router.handleBack()) {
        super.onBackPressed();
    }
}
```

**Comment by burhanrashid52** [comment]
Yes..

**Comment by EricKuck** [comment]
One of your child controllers must be handling the back button event. Without any code I can't tell what the issue is though.

**Comment by Reline** [comment]
I'm not sure if it's exactly what @burhanrashid52 is experiencing, but I was having a similar issue which I reproduced [here](https://github.com/Reline/ConductorTest/tree/6cd15c01422f0948c4678372e02c098ae858c1c3).

I have a single home controller, which sets the root controller on a single child router and calls the restore and save on that child router to preserve the views. Now when I push another child controller on top of a root controller, I can press the back button to pop it off. But if I were to leave that root and come back while the child controller were still pushed, the back button now closes the activity instead of popping the child controller. Am I doing something wrong?

**Comment by EricKuck** [comment]
The `saveInstanceState` and `restoreInstanceState` methods weren't really meant to be used by developers. They should have probably been package-private, but I guess it's too late for that now. I'm curious why you're doing it that way? What problem does this solve?

**Comment by Reline** [comment]
I'm using the BottomNavigationView and modeled my ControllerManager similarly to the ViewPager example you made, where there is one host controller (my HomeController) and one child router that has its root controller swapped out. Those controllers can then also have controllers pushed onto them as well, but I still want to have the option to navigate to one of my other root controllers and preserve the state of that pushed stack.

Is this the correct approach or would you recommend another solution?
