### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by seato** [bluelinelabs/Conductor#197]
Swipe right on "Drag to Dismiss" on the view "Elastic scrolling view..." and you transition into the Child Router Demo.

**Comment by EricKuck** [comment]
Thanks for the heads up. This was caused because the home controller asks to not be removed from the view when the "Drag to Dismiss" controller is pushed. Since it was still there behind the view, clicks actually went through the header view and registered as a touch on the RecyclerView behind it. It just so happened that the child router demo was the row below that view. All fixed now.
