### ISSUE TITLE
README shows wrong usage of Controller API

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bluelinelabs/Conductor#2]
In a Controller, the only method we need to override is:

```java
    @NonNull
    @Override
    protected View inflateView(LayoutInflater inflater, ViewGroup container) {
        return null;
    }
```

But README shows:

```java
    @Override
    protected int layoutId() {
        return R.layout.controller_overlay;
    }

    @Override
    public void onBindView(@NonNull View view) {
        super.onBindView(view);

        ((TextView)view.findViewById(R.id.tv_title)).setText("Hello World");
    }
```

**Comment by EricKuck** [comment]
Good catch! The implementation in the readme was leftover from when this was an internal project for our company. I replaced `layoutId()` with `inflateView()` in the readme. I did leave `onBindView()` though, because I believe it's better to separate inflating and binding (although doing all the work in `inflateView()` work work too).

**Comment by cs-victor-nascimento** [comment]
Yeah I agree with the separation too. It was to help pointing out the difference in documentation.

I am experimenting with Conductor here and might create other issues in the following days :)

**Comment by EricKuck** [comment]
Sounds great! I'd love to hear whatever feedback you have. We've been using it for a while now and are big fans, but we might be a little biased :)
