### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by serjooo** [bluelinelabs/Conductor#237]
What is the right way of notifying a controller that data from server has been changed from another controller? I am also using the MVP pattern. 

In my case I launch an overlay controller, from the controller that I want to be notified, I add lets suppose a new note to the server the presenter calls the view to be popped go back to the previous controller. Now I need the adapter to be updated. 

Should I use the observable pattern? Or I don't need to go into that for something this simple?

I attempted to just call notifyDataSetChanged on the adapter onAttach view, but since its an overlay controller the previous controller's view is never being destroyed to call onAttach again.

**Comment by EricKuck** [comment]
There's a `setTargetController` method you can call. So ControllerA opens ControllerB, ControllerB does some work, and when it's done, calls a method on ControllerA to tell it to update.

If you want to do it the way Fragments do it, you can call `onActivityResult`. That always felt kinda dumb to me though, since it's so poorly named and since you have to wrap everything in an Intent. 

My recommendation would be to have ControllerB declare a callback interface that ControllerA would implement.

**Comment by serjooo** [comment]
Thank you very much I'll try what you recommended. I thought of implementing an interface too seemed most logical. 

Again thanks for your time and great work on Conductor made Android development 100 times simpler!
