### ISSUE TITLE
Child Controller options menu?

### ISSUE THREAD

**Issue by mkpowers** [bluelinelabs/Conductor#26]
Hi,

Using `setHasOptionsMenu()` in a child controller from a ControllerPagerAdapter doesn't seem to call any of the options menu-related callbacks. Is this intentional? Love the library!

Thanks!

**Comment by EricKuck** [comment]
Thanks for the report. This was not intentional and will be fixed within the next day or two. 

One thing to note is that, when this is fixed, options menus will appear when the controller is attached, not necessarily when they're the center page in a ViewPager, so it might take a little work to get your situation working the way you're expecting. The same caveat is true with Fragments.

**Comment by EricKuck** [comment]
I haven't had a chance to test this very well yet, but f6493507f49d49c3ebeb8a4887d44987a642869d should fix this issue. Snapshot releases aren't yet setup, but I'll be testing this and releasing it as a snapshot within the next few days.

**Comment by EricKuck** [comment]
This is now available in `1.1.5-SNAPSHOT` and should be pushed within the next week or two as a standard release.
