### ISSUE TITLE
attach/detach do not get called in order

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#266]
When pushing a new controller with a change handler immediately after I have set another controller, onAttach of the first controller does not get called. Note, that In B I pop the controller immediately.
Looks quite simmilar to #256 for me.

```java
public class MainActivity extends AppCompatActivity {

  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    ViewGroup container = (ViewGroup) findViewById(android.R.id.content);
    Router router = Conductor.attachRouter(this, container, savedInstanceState);
    if (!router.hasRootController()) {
      router.setRoot(RouterTransaction.with(new A()));
    }
    router.pushController(RouterTransaction.with(new B()).pushChangeHandler(new FadeChangeHandler()));
  }

  public static class A extends Controller {

    @NonNull @Override protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
      return new View(getActivity());
    }

    @Override protected void onAttach(@NonNull View view) {
      super.onAttach(view);
      Log.d("A", "onAttach");
    }

    @Override protected void onDetach(@NonNull View view) {
      super.onDetach(view);
      Log.d("A", "onDetach");
    }
  }

  public static class B extends Controller {

    @NonNull @Override protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
      return new View(getActivity());
    }

    @Override protected void onAttach(@NonNull View view) {
      super.onAttach(view);
      Log.d("B", "onAttach");
      getRouter().popController(this);
    }

    @Override protected void onDetach(@NonNull View view) {
      super.onDetach(view);
      Log.d("B", "onDetach");
    }
  }
}
```

Without change handler:
```
D/B: onAttach
D/B: onDetach
D/A: onAttach
```

With change handler:
```
D/A: onAttach
D/B: onAttach
D/B: onDetach
```

I found this because I set the statusbar color in onAttach but was left with the statusbar color from Controller B and not A.

**Comment by EricKuck** [comment]
I'm not sure what the correct solution for this is. I replicated what you had and controller A's view actually never does get attached to the window. It seems like the callbacks are correct, even if they're not what you'd expect. What do you propose?

**Comment by PaulWoitaschek** [comment]
>  I replicated what you had and controller A's view actually never does get attached to the window until after B is popped.

My problem is that with the change handler controller A gets attached but not detached when B gets attached. So there are 2 Controllers attached at the same time.

I expected that last controller that gets attached is the one visible.

**Comment by PaulWoitaschek** [comment]
Any news on this? This is a real issue for me.

**Comment by EricKuck** [comment]
I'm still not quite sure what the more correct behavior would be in this case. Since B is almost instantaneously pushed and popped, the change handler never completes and never actually gets to the point where it detaches A's view. By the time `AnimatorChangeHandler.performAnimation` is called, the change handler has already been canceled and nothing happens.

Do you have a proposal for this situation?

**Comment by PaulWoitaschek** [comment]
So are there actually 2 views attached at the same time? Can't B wait for A to detach? Or tell it somehow to skip its animations, something like `jumpToCurrentState` for drawables?

I'm not sure what a good solutio is here but I also don't fully understand the intrinsics of Conductor. But right now there is no safe way to say which controller is acutally being shown.

**Comment by sockeqwe** [comment]
Maybe I'm missing something or have misunderstood your question but,

you may have more than 1 controller attached / shown anyway if you have a tablet layout or a master-detail layout. So I don't think that in general you should relay on having only 1 Controller attached at all.
 
Also lifecycle events `Controller.onAttach()` and `Controller.onDetach()` are reflecting the event when Controller's view (returned from `Controller. onCreateView()` is attached / detached  to / from the window. 
So when 2 Animation run like a fade animation you have 2 controllers attached anyway (otherwise you can't animate) and the lifecycle `onDetach()` is called when the view has been removed from parent / detached from window.


Since conductor is not coordinating animations of `ChangeHandlers` (which btw. is a great design decision) it is not easy to "skip" the animation. I think this is out of scope and your responsibility as developer of your app. 

i.e. you can write a custom `ChangeHandler` that sets the status bar color when the animation is completed. Also, you can write a component that coordinates your custom change handlers / animations of your `ChangeHandler` and  "skip" a animation if required.

**Comment by PaulWoitaschek** [comment]
Okay. Then I'll close this one if there is no simple solution for knowing which controller is really visible to the user.
