### ISSUE TITLE
RouterPagerAdapter recreates controllers silently

### ISSUE THREAD

**Issue by sewar** [bluelinelabs/Conductor#269]
It looks like controllers might get recreated silently when using RouterPagerAdapter.

To reproduce:
1. Apply [this patch](https://gist.github.com/sewar/6aebfd0ba606d13917d2b8e0e2cc516b).
2. Open ViewPager demo.
3. Rotate your device screen, notice the page controller hash code is changing.

There's a similar issue in Master/Detail demo:
1. Tap on an item while in portrait mode.
2. Rotate your device screen, the same controller is still shown there correctly.
3. Click back, the details controller is recreated.

**Comment by daniil-vinogradov** [comment]
I have the same problem. onDestroy is called for Controllers in ViewPager

**Comment by respect12rus** [comment]
I also have this problem on Samsung galaxy S6.

**Comment by EricKuck** [comment]
Thanks for all the details on this one! The controllers were being recreated because of the `setPagerAdapter(null)` call that always happened in `onDestroyView`. This now only happens if the Activity isn't undergoing a configuration change in the demo app. There wasn't an issue in the core library, just in the example that was out there. You should be able to fix this in your app without a dependency update.

**Comment by sewar** [comment]
Thanks.
