### ISSUE TITLE
Nested RouterPagerAdapter setting wrong current item

### ISSUE THREAD

**Issue by ersin-ertan** [bluelinelabs/Conductor#271]
Both `Root Cont` and `A` have `RouterPagerAdapter`s
```
[Activity]
[Root Cont] 
[ A ]  [ B ]
[A1][A2]
```

On rotation, `Root Cont` and `A` both set the current item to `A` and `A1` respectively.
However, if `A` swipes from `A1` to `A2`, then a rotation, `Root Cont` will incorrectly set the current item to  `B`. Note that swiping back to `A` will show `A2` which was the correct item to set.

https://github.com/ersin-ertan/RouterPagerAdapterBug

**Comment by EricKuck** [comment]
This actually has nothing to do with Conductor, but with the way the ViewPager saves its own state. State saving for ViewPager is keyed off its id field. Since you have 2 nested ViewPagers that have the same id, they end up sharing the same state after restoration. You'd see the same issue if you did the same thing without Conductor. Change one of them to `viewpager2` or whatever and it'll work great.
