### ISSUE TITLE
[Question] Why not Java 6?

### ISSUE THREAD

**Issue by mrgalwen** [bluelinelabs/Conductor#275]
Why are you using Java 7 instead of Java 6? Is it used only for the diamond braces feature? 

I noticed that minSdkVersion is 16, but Java 7 works on SDK 19 and above, IMHO this is some sort of inconsistency.

**Comment by EricKuck** [comment]
JDK 1.7 works fine with older versions of Android. What's the problem with using it? I'm not a masochist.

**Comment by mrgalwen** [comment]
Sorry, I meant Java 6 not JDK 1.6 (I changed title and question content).

You have set parameters:
```
sourceCompatibility JavaVersion.VERSION_1_7
targetCompatibility JavaVersion.VERSION_1_7
```
in your build.gradle files.

If I am using for example Kotlin Lang and compatibility with Java 6 I can use SDK 16 as minSdkVersion and then my application is compatible with Android 4.1 and above. At now Conductor library has not compatible bytecode with Java 6 and application does not compile.

**Comment by EricKuck** [comment]
Java 7 code compiles just fine for older versions of Android. The only Java 7 feature that you can't use below KitKat is try-with-resources. It's been this way since October 2013 (http://tools.android.com/recent/androidstudio032released). This library has been used in apps with minSdk 16 plenty of times with no issues.
