### ISSUE TITLE
[Question] Popping Controler with back pressed does not call onSaveInstanceState

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bluelinelabs/Conductor#28]
This was odd to me, but pressing the back button on a controller (that does not override `handleBack()`) should pop it. This works well but I thought it would call all the lifecycle methods such as `onSaveInstanceState()` which isn`t called.

Am I missing something obvious here?

**Comment by adi1133** [comment]
When popping a controller, you are destroying a controller with no intention of recreating it later.

OnSaveInstanceState is not called because the controller will not be recreated later by the framework.

OnSaveInstanceState is called before the controller may get destroyed by the android framework. Activity going to background causes a save because the app maybe killed without any notification.

**Comment by cs-victor-nascimento** [comment]
Yep. Dumb question... I thought it was called even when you call finish from an Activity. Should have checked first.
