### ISSUE TITLE
onAttach with isDestroyed=true

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#287]
I have a use case where when the user clicks a tab in a view pager, it pushes another controller instead an resets the position of the view pager.

Now with 2.1.3 I receive crashes because onAttach of a controller is being called after it is destroyed (its onDestroyView) was called and I nulled a variable in onDestroyView I now access in onAttach.

```kotlin
class MainActivity : AppCompatActivity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val container = findViewById(android.R.id.content) as ViewGroup
    val router = Conductor.attachRouter(this, container, savedInstanceState)
    if (!router.hasRootController()) {
      router.setRoot(RouterTransaction.with(RootController()))
    }
  }

  class RootController : Controller() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
      val pager = ViewPager(activity!!)
      pager.adapter = Adapter(this)


      Handler().postDelayed({
        pager.setCurrentItem(2, true)
        router.pushController(RouterTransaction.with(LoggingController()).pushChangeHandler(FadeChangeHandler()))
        pager.setCurrentItem(0, true)
      }, 2000)

      return pager
    }
  }

  class Adapter(host: Controller) : RouterPagerAdapter(host) {
    override fun configureRouter(router: Router, position: Int) {
      if (!router.hasRootController()) {
        router.setRoot(RouterTransaction.with(LoggingController()))
      }
    }

    override fun getCount() = 3
  }

  class LoggingController : Controller() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup) = View(activity!!).apply {
      val rnd = Random()
      val color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256))
      setBackgroundColor(color)
    }

    override fun onAttach(view: View) {
      Log.d(toString(), "onAttach with isDestroyed=$isDestroyed")
    }

    override fun onDestroyView(view: View) {
      Log.d(toString(), "onDestroyView")
    }
  }
}
```

This logs:
```
D/de.paul_woitaschek.conductoronattachbug.MainActivity$LoggingController@11c05d2: onAttach with isDestroyed=false
D/de.paul_woitaschek.conductoronattachbug.MainActivity$LoggingController@6becda0: onAttach with isDestroyed=false
D/de.paul_woitaschek.conductoronattachbug.MainActivity$LoggingController@3f4b0b8: onDestroyView
D/de.paul_woitaschek.conductoronattachbug.MainActivity$LoggingController@3f4b0b8: onAttach with isDestroyed=true
D/de.paul_woitaschek.conductoronattachbug.MainActivity$LoggingController@1a02064: onAttach with isDestroyed=false
D/de.paul_woitaschek.conductoronattachbug.MainActivity$LoggingController@11c05d2: onDestroyView
D/de.paul_woitaschek.conductoronattachbug.MainActivity$LoggingController@6becda0: onDestroyView
```

**Comment by PaulWoitaschek** [comment]
Forgot to mention:

This problem is introduced in 2.1.3

**Comment by EricKuck** [comment]
I'd like to revert the change from 2.1.3 that defers `onAttach` until the next run loop, as it seems to be causing other problems. The problem is that there's an Android issue that I'm not sure how to work around without this. One of your previous examples (#274) crashes with the following stacktrace if we don't let the Looper complete all of the work it has to do on attach:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2924)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
at android.view.Choreographer.doCallbacks(Choreographer.java:686)
at android.view.Choreographer.doFrame(Choreographer.java:621)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

It's not safe to call any methods that immediately remove a view from the hierarchy directly from the `onViewAttachedToWindow` callback, as Android will continue to expect the view to be there for a few more method calls. 

From what I can see, the options would be to either tell people they can't pop a view from `onAttach` or to continue down the road of making ALL callbacks defer for the next run loop. Both seem like bad options. Any ideas?

**Comment by EricKuck** [comment]
For some reason I left the relevant code from ViewGroup out of my last comment. The relevant code that makes it impossible to remove a view from the hierarchy on the `onViewAttachedToWindow` callback is this:

```
        final int count = mChildrenCount;
        final View[] children = mChildren;
        for (int i = 0; i < count; i++) {
            final View child = children[i];
            child.dispatchAttachedToWindow(info,
                    combineVisibility(visibility, child.getVisibility()));
        }
```

Removing a view when the callback occurs will decrement the `mChildrenCount` variable, but the for loop will continue iterating on the previous value. So we have to somehow prevent the user from making this mistake, either through deferring the `onAttach` call, disallowing `pop` events during `onAttach`, or perhaps making `ControllerChangeHandlers` that attempt to execute while in this state wait until the next run loop? It seems like maybe postponing change handlers is the way to go - any opposition to this?

**Comment by PaulWoitaschek** [comment]
This goes beyond my understanding. 

@JakeWharton @sockeqwe Any thoughts?

**Comment by EricKuck** [comment]
I took a stab at fixing this issue at the change handler level instead of being heavy-handed with when `onAttach` occurs. It seems to work quite well from my tests so far, but there's lot of edge cases I haven't tried yet. If you check out the latest snapshot build you can try it out.

**Comment by sockeqwe** [comment]
SorrY, I haven't followed the discussion and recent internal conductor changes  so that I can't  give any feedback on this.

**Comment by EricKuck** [comment]
This should now be fully working in the latest snapshot. I plan to do a release soon, so please check it out and make any comments you have.

**Comment by soniccat** [comment]
I see the solution doesn't work in the case of rotation to portrait when we launch a portrait only app in landscape. In this case app starts in landscape and immediately rotates. That leads to "performPendingControllerChanges" won't be called as router container will be destroyed. So, that breaks Conductor completely as ALL next performControllerChange requests will be postponed because of "if (pendingControllerChanges.size() > 0)" check.

A probable solution is to call performPendingControllerChanges in watchContainerAttach in post too.

@PaulWoitaschek @EricKuck btw is Conductor support abandoned? Our team really like it and I'd like to fix issues I find. Now it seems nobody checks pull requests and Issues (I filled one a month ago). Is the fork the only option or there is any other solution for me to be able to fix issues I find?
