### ISSUE TITLE
[Question] redundant views while using deeply nested controllers

### ISSUE THREAD

**Issue by SaeedMasoumi** [bluelinelabs/Conductor#288]
Hi,
Is it possible to create a controller with no forces to create a view? 

Because when we use nested child controllers we must define a view for each one and sometimes it's not necessary and causes redundant views.

**Comment by EricKuck** [comment]
What would a controller do if not display a view? A controller is designed to be the view layer of your app, so not requiring a view makes the concept of a controller meaningless. Why not use another component if you have nothing to show the user?

**Comment by EricKuck** [comment]
Ah that might be. But even the PR doesn't work without a View. What do `onAttach` and `onDetach ` mean without a view?

**Comment by SaeedMasoumi** [comment]
@EricKuck @PaulWoitaschek actually i want to implement [uber's](https://eng.uber.com/deep-scope-hierarchies/) architecture with condcutor

**Comment by EricKuck** [comment]
You can implement their architecture, you just can't (and shouldn't) use a controller as your scoping mechanism. Their criticism of conductor was because they tried to shoehorn their deep scoping idea into a controller, when it should really be a separate unit if you're going to use this library. A controller is meant to be the view layer of your app, not a data or logic layer.
