### ISSUE TITLE
Avoiding controller recreation after process restart

### ISSUE THREAD

**Issue by inorichi** [bluelinelabs/Conductor#293]
Is there a recommended way to avoid recreating a controller after a process restart?

I have a dialog controller doing an operation I don't want to restart if the process is killed (nor have an infinite progress dialog when it happens).

I'm currently calling `router.popController(this)` in `onRestoreInstanceState` and it's working, but it seems fishy so I'm wondering if this is a good practice or it would make sense to implement in Conductor as a  parameter or method.

I'm thinking of a key in the controller's bundle that is retrieved before creating it, and if the condition is met, the controller isn't created/added to the backstack (I haven't read the internals so much, so I don't know if this is feasible).

But handling this in the library creates another problem, what would happen if in `[A, B, C]`, `B` is set to not recreate? Would `C` be ignored too (`[A]`) or would it be created (`[A, C]`)?

Thoughts?

**Comment by sockeqwe** [comment]
> I have a dialog controller doing an operation I don't want to restart if the process is killed (nor have an infinite progress dialog when it happens).

Put that outside of the lifecycle of a controller i.e. service, JobScheduler, Database etc.

Think controller as View Layer that just displays things. 
The other is "business logic". 
If DialogController is recreated but background task is already done, then you can simply pop the dialog controller immediately (without animation) so that the user doesn't see it at all (or show a "job done" info in the dialog and then pop dialog controller)

**Comment by inorichi** [comment]
I usually have a presenter doing background tasks.

I was more concerned about removing a controller in `onRestoreInstanceState`, but from what I've seen, it works just fine.

Closing, thanks.
