### ISSUE TITLE
[Question] Is there any example about integrating drawer and toolbar with Conductor?

### ISSUE THREAD

**Issue by thebrokenbar** [bluelinelabs/Conductor#333]
I'm looking for any sample about integration Toolbar and Drawer with Conductor.

**Comment by EricKuck** [comment]
I don't know of any samples like this, but there's nothing special about Conductor that would make this different from any other sample that uses a Toolbar and Drawer. The demo app actually does use a Toolbar BTW, just not a drawer.

**Comment by thebrokenbar** [comment]
@EricKuck Thanks for a reply. My problem is not just a Drawer or simple Toolbar. I'm trying to implement fully integrated Toolbar with navigation etc. Something like Android's fragments has out of the box. Just encountered some problems and i'm wondering if it's a known issue for others. When router's backstack is changed I expect Toolbar to change Drawer icon and handle back navigation. It's not happening. Setting some listeners to handle back navigation and switch "hamburger" icon with "arrow" manually seems like too much work for a "Android fragment replacement" which Conductor is.

**Comment by EricKuck** [comment]
What API are you referring to that handles this automatically for
Fragments? I’m not aware of anything like that.


On July 27, 2017 at 3:06:32 PM, thebrokenpipe (notifications@github.com)
wrote:

@EricKuck <https://github.com/erickuck> Thanks for a reply. My problem is
not just a Drawer or simple Toolbar. I'm trying to implement fully
integrated Toolbar with navigation etc. Something like Android's fragments
has out of the box. Just encountered some problems and i'm wondering if
it's a known issue for others. When router's backstack is changed I expect
Toolbar to change Drawer icon and handle back navigation. It's not
happening. Setting some listeners to handle back navigation and switch
"hamburger" icon with "arrow" manually seems like too much work for a
"Android fragment replacement" which Conductor is.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bluelinelabs/Conductor/issues/333#issuecomment-318471594>,
or mute the thread

**Comment by thebrokenbar** [comment]
@EricKuck supportActionBar.setDisplayHomeAsUpEnabled() changes home button to navigation element.

**Comment by EricKuck** [comment]
That call doesn't have anything to do with Fragments though. Why can't you do the same thing with Conductor?

**Comment by EricKuck** [comment]
Nevermind, I get what you're saying. I could add all the supportActionBar stuff to Controllers, but honestly I feel like that needs to be deprecated. The actionbar paradigm is pretty outdated. @ZakTaccardi wrote a good article about this subject a while back: https://medium.com/@ZakTaccardi/goodbye-actionbar-apis-hello-toolbar-af6ae7b31e5d

**Comment by thebrokenbar** [comment]
@EricKuck This is exactly what I was thinking. So there is no "build in" mechanism in framework. Thanks, this is answer that I was looking. I will just continue my work. Thank you once more
