### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by dzeroone** [bluelinelabs/Conductor#369]
How to work with Splash Screen?
1. Should I attach router on `MainActivity` and then fire `SplashController`?
2. Should I start `SplashActivity`, then fire `MainActivity`, attach router on `MainActivity`?

**Comment by sockeqwe** [comment]
Whatever works best for you.

I would go with option 1.

dzeroone <notifications@github.com> schrieb am Di., 17. Okt. 2017 um
10:00 Uhr:

**Comment by dzeroone** [comment]
Thanks.
But with `option-1` I have to do extra work with `AppNavigationBar` how should I handle it?

**Comment by sockeqwe** [comment]
put navigation bar into a RootController. Swap SplashScreenController with
RootController

dzeroone <notifications@github.com> schrieb am Di., 17. Okt. 2017 um
10:15 Uhr:

**Comment by PaulWoitaschek** [comment]
I prefer to have multiple activities so I have a SpashActivity in my current project that either starts the Main activity or the sign up activity.

That keeps the logic the activity that hosts router scoped.

**Comment by EricKuck** [comment]
Be careful if you do option 2. I've seen a lot of terrible implementations of this that end up punishing users for accidentally launching their apps. The flow goes: accidentally launch app, immediately hit home or back, then X seconds later get the app you just dismissed launching its main activity over the top of whatever you were actually trying to do.

**Comment by dimsuz** [comment]
> The flow goes: accidentally launch app, immediately hit home or back, then X seconds later get the app you just dismissed launching its main activity over the top of whatever you were actually trying to do.

I guess this would be eliminated if you would do `startActivity(MainActivity); finish(); return` from `SpashActivity.onCreate()`. IIRC this would also ensure that no animations/etc would be shown for MainActivity which would exclude flicker.

**Comment by PaulWoitaschek** [comment]
I think what he talks about is using a handler and not removing the runnable when the activity pauses.

**Comment by PaulWoitaschek** [comment]
Bwaha, that bug affects my current application too. 

But I'm not alone.
Google Fit,
Google Drive,
...

😂

**Comment by dimsuz** [comment]
Yeah, splash screens will never work on Android, because Android apps were designed with the "app is always ready" approach in mind. And Android System does a lot of things to adhere to this principle, to make it appear like this is the case even if app is restarted under the hood. That's why we have all those instance state saving etc.

I.e. it is designed like there is NO point where you can say _"this app was just started"_ or _"this app was just stopped"_. It's rather: _"you stopped using this app"_, _"you are back! please continue where you left off"_...

I don't know why Google decided to go a "Launch screen" route. Because it breaks their own system's design rules :) And all their apps are broken in regards to this.

I constantly see a Splash Screen after I go BACK in a Google Music (from some album to My Library). It makes me cringe every time :)
