### ISSUE TITLE
@NotPersisent Annotation

### ISSUE THREAD

**Issue by leonardo2204** [bluelinelabs/Conductor#40]
Shouldn't be nice to have a "@NotPersistent" annotation, so when moving to one Controller to another, maybe you don't want to save the "backstack" Controller.
For example: You have a screen with people list, you add a new person, close the current insertion Controller and go back, the list will be saved at the previous position (when the user clicked the '+' button).

**Comment by adi1133** [comment]
You can pop the current controller before pushing the new one, or just use replaceTopController()

**Comment by leonardo2204** [comment]
I know that, but wouldn't it be easier to simply annotate a Controller with an annotation and skip the saveViewState process ?

Date: Fri, 29 Apr 2016 11:42:26 -0700

**Comment by adi1133** [comment]
You can subclass the Controller class yourself and add such functionality, maybe even publish it online.
If we add something like this to the core lib we need documentation, more code, more runtime reflection and unit tests for a feature that is already easy to implement by an app dev.

**Comment by EricKuck** [comment]
I'm not big on the use of runtime annotations for stuff like this, and tend to agree with @adi1133 that this feels like more of a base controller implementation detail (or using `replaceTopController` instead of pushing a new one). 

My main argument against an annotation for this purpose, besides the stuff mentioned above, is that it reduces reusability of controllers. If the mechanism for preventing a controller from being added to the backstack is an annotation, and you have a controller that is conditionally added or not added to the backstack, you're going to have to do two separate controller implementations.

**Comment by mheras** [comment]
I agree with @adi1133 and @EricKuck. It would be great to keep the library free of annotations (not a big fan either).

**Comment by leonardo2204** [comment]
Ok then, thanks! 

Date: Fri, 29 Apr 2016 17:31:54 -0700
