### ISSUE TITLE
Question: Is the Conductor Project still Active?

### ISSUE THREAD

**Issue by Lancelittle** [bluelinelabs/Conductor#401]
Just wanted to check if the project is still active before I implement it in a few projects. I noticed that the last commit was back in October.

**Comment by serjooo** [comment]
In my opinion I think the project is fairly kind of complete in a sense that you could use it for projects. I personally, have developed two projects using conductor, and developing another one right now and I haven't had Conductor stop me from achieving anything. Moreover, I think the community and users have fairly grown so much and everybody would be ready to help. If you are worried that Conductor might die some out, I highly doubt it.

**Comment by dimsuz** [comment]
I agree that it is complete and working, but still any project needs to be maintained to stay afloat. Even in no-new-features mode: dependencies change, Android changes, some bugs get discovered (and still there are some more or less major ones not fixed in current version, mostly child-controller related).

Haven't seen @EricKuck answers to issues for a while now, a bit worried too. Maybe he's on long vacation or has some important stuff happening who knows. 

Anyways Conductor is really great at the moment, let's hope it stays that way! :)

**Comment by EricKuck** [comment]
You're right, I haven't been as active as I had been in the past. I'm currently on a really, really large project and am just swamped with work, so less time has gone into open source than I'd like. The project is definitely not dead, just moving slower for a season.

That being said, I think @serjooo touched on an important thing - the community. Currently I'm the only core maintainer for the library, and therefore it moves at the speed that I can manage. I'd like to change that by getting others involved more. Anyone have suggestions how we can make that happen?

**Comment by serjooo** [comment]
@EricKuck I suggest as a start we could set milestones on what features should be implemented and bugs should be fixed and a call for maintainers in the README. Also, maybe a Slack channel for Conductor would be really helpful!

**Comment by dimsuz** [comment]
Also it would be nice if someone could help with PRs as they appear. But that must be someone who knows codebase very well, because I'm sure there's a ton of tiny details and corner cases which could easily be missed (in case some of them are not covered by tests).

From what I observed @PaulWoitaschek helped many times to fix or spot some issues, maybe he'll be willing to help here or other people who took more or less deep dive into this library :)

**Comment by hannesstruss** [comment]
@EricKuck glad you're alive :)

I think the biggest issue to tackle is the growing backlog of PRs and issues. I'm not super deep in the Conductor code, but I'm happy to help more with triaging issues, pointing people to StackOverflow etc.

**Comment by gstepniewski** [comment]
It seems like there is a bunch of issues that either have been resolved or are invalid - closing those down would probably be a good start?

**Comment by Zhuinden** [comment]
One day, `2.1.5-SNAPSHOT` will stop being snapshot :smile:

**Comment by EricKuck** [comment]
I just took a first stab at a pretty robust set of contribution guidelines that should really move this project along. Any thoughts? https://github.com/bluelinelabs/Conductor/blob/develop/CONTRIBUTING.md

**Comment by mario** [comment]
Looks good @EricKuck.
