### ISSUE TITLE
Don't allow pushing a controller several times

### ISSUE THREAD

**Issue by SamYStudiO** [bluelinelabs/Conductor#425]
We can push the same controller instance over and over again with a router, this can lead to weird behaviour, should'nt an already added controler instance be ignore when trying to push it again?

**Comment by joaolisboa** [comment]
Could you give more details on what issues you're having and the implementation? I don't think this should happen. Conductor allows you to use a TAG to 'describe' your controller(or controller instances if you desire) for you to handle your own navigation logic but even when you use a TAG I don't think conductor cares about it other than allowing you to get the controller from the router with it.

**Comment by SamYStudiO** [comment]
Check and run this project https://github.com/SamYStudiO/beaver.
On home screen click invalidate which push current controller instance to same router and see how view disappear on next screen, then go back and click invalidate again and then of course you get a crash since controller has just been destroyed.
That's the king of weird behaviour i am talking and i think it could be avoid if adding an already added controller was simple ignored or if it throws immediatly an exception explaining that controller is already added to stack.

**Comment by joaolisboa** [comment]
router.pushController(RouterTransaction.with(this)...

Well you are pushing the same instance, of course, once the view is destroyed they're both(really just one) destroyed. You have to create a new instance. This isn't an issue with Conductor checking whether or not it's instanced, you gave it the same instance so this behavior is expected. Everything is working as intended, in other words, the issue is in your implementation, nothing else. If you don't mind me asking, what's the purpose of pushing the same controller instance again?

**Comment by PaulWoitaschek** [comment]
I think that conductor fails here because pushing a controller multiple times sets the library in an invalid state.

I suggest to iterate the backstack and throw an exception if that controller is already in the backstack.

I can do a PR for that if this is wanted @EricKuck

**Comment by SamYStudiO** [comment]
I don't want to push a controller several time, i'd like conductor to check this internally , since i think this shouldn't be allowed. In most cases (if not all cases) this will lead to unexcpected behaviours and crashes.

**Comment by joaolisboa** [comment]
I get that but if there are unexpected behaviors or crashes it's the fault of whoever wrote that code, Conductor shouldn't have to check the current backstack, you're the one in control of it, if you push the same instance you should expect these issues. 

@PaulWoitaschek It's not the library that's set into an invalid state, it's the developers own Controller and app navigation since it was improperly designed. Throwing an exception might help someone who makes a mistake and make it easier to understand the issue, which I think is an issue that shouldn't happen in the first place but I guess you never know.

**Comment by SamYStudiO** [comment]
I'm not sure this has to be user responsability, what's the point of IllegalStateException or ArgumentException for example, we shouldn't throw these because this is the user responsability to do things right?

**Comment by PaulWoitaschek** [comment]
> we shouldn't throw these because this is the user responsability to do things right?

I think only to some degree. 

I think a library should always validate all user inputs and throw if it's not being used properly. Also the internals look like they are really not designed to handle having a controller instance multiple times in the backstack.

**Comment by joaolisboa** [comment]
@SamYStudiO As said above, only to some degree. I can see the need for such exception, but personally, I just think this is such an obvious no-no when designing navigation that I don't even consider this an issue. In the off chance it does happen due to some mistake in navigation, sure, go for it.
