### ISSUE TITLE
How to pop all controllers including the root one in one step from a child router?

### ISSUE THREAD

**Issue by kaciula** [bluelinelabs/Conductor#438]
As it is said in the title, I want to pop all controllers from a child router in one go. What I am doing now is calling popToRoot(), setPopsLastView(true) and popCurrentController(). But this means the root controller calls onCreateView() right before I pop it and also the changehandler of the root controller is called. It's not visually appealing.

So I want a method that pops ALL controllers from a child router in one single step. Is this possible?

**Comment by chris6647** [comment]
The only solution I know of, is to do something like the RouterPagerAdapter does, or as I do in my BottomNavigationController (https://github.com/bluelinelabs/Conductor/pull/316) and call  removeChildRouter(childRouter) to destroy the childRouter, and then recreate it.

Otherwise, depending on what exactly you're trying to achieve, setting a new backstack all together may be good enough for you.

**Comment by kaciula** [comment]
I did try setting an empty backstack but the visible controllers were not popped from the screen for some reason.

Will try the removeChildRouter() approach. Thanks.

**Comment by kaciula** [comment]
removeChildRouter() was exactly what I needed. Thanks.
