### ISSUE TITLE
onConfigurationChanged callback

### ISSUE THREAD

**Issue by dbof10** [bluelinelabs/Conductor#488]
In some scenario, I need to react on `onConfigurationChanged`. Any thought on this?

**Comment by joaolisboa** [comment]
What scenario are you trying to solve?

In my app I have a nested router, so basically I have an Activity with my root router with a single RootController. In my RootController I have a router and handle all my navigation there instead of the activity. If necessary, I can grab these Activities callbacks and send them to the RootController. I solved a scenario this way:

 - Activity gets info on a barcode that was read by a scanner. 
 - The activity calls `getRootController().sendBarcodeData()`.
 - The RootController then calls `onBarcodeScanned()` in the Controllers that implement the interface `BarcodeScannerListener` so whenever I need to react to reading a barcode on any view I just implement the method.

You don't need a RootController to solve this, you could just send it directly to the Controllers you need, but it is a solution and I'm sure there might be better solutions.

**Comment by dbof10** [comment]
for my case, I have to do some works `onConfigurationChanged ` . It's nice to have the callback. I think we can close now
